deployment:
  tasks:
    - export DEPLOYPATH=/home/experience1/markide/
    - mkdir -p $DEPLOYPATH   
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp style.css $DEPLOYPATH
    - /bin/cp -R images $DEPLOYPATH
